---
image: nixos/unstable
packages:
  - nixos.cosign
  - nixos.docker-client
  - nixos.git
  - nixos.gnupg
  - nixos.go
  - nixos.goreleaser
  - nixos.openssh
  - nixos.syft
secrets:
  - 0a0692e0-075e-4616-9aeb-6d51472edd94
  - 4dcaff42-1274-4f62-8f06-c8012f6ba70c
  - 53890b2b-3281-4eaa-a466-9eda188b07bf
  - 76d9985f-f5da-4a19-816d-19ad1afa7f5d
tasks:
  - test: |
      set +x
      . "$HOME/clilol-secrets.sh"
      set -x
      cd clilol
      go test ./...
  - release: |
      rhs="${GIT_REF#*/}"
      reftype="${rhs%/*}"
      refval="${rhs#*/}"
      if [[ $reftype == "tags" ]]; then
        set +x
        . "$HOME/clilol-secrets.sh"
        echo "$GITEA_TOKEN" | docker login -u mcornick --password-stdin git.mcornick.dev
        set -x
        cd clilol
        goreleaser
      fi
triggers:
  - action: email
    condition: failure
    to: mcornick@mcornick.com
