---
image: alpine/latest
packages:
  - coreutils
  - cosign
  - curl
  - docker-cli
  - git
  - gnupg
  - go
  - syft
secrets:
  - 0a0692e0-075e-4616-9aeb-6d51472edd94
  - 4dcaff42-1274-4f62-8f06-c8012f6ba70c
  - 53890b2b-3281-4eaa-a466-9eda188b07bf
  - 76d9985f-f5da-4a19-816d-19ad1afa7f5d
  - 7e064e16-8d36-4db0-ab30-e98b3fe88436
  - c62dc5b4-3b39-48be-84cc-8283c38f1933
tasks:
  - test: |
      set +x
      . "$HOME/clilol-secrets.sh"
      set -x
      cd clilol
      go test ./...
  - release: |
      rhs="${GIT_REF#*/}"
      reftype="${rhs%/*}"
      refval="${rhs#*/}"
      if [[ $reftype == "tags" ]]; then
        set +x
        . "$HOME/clilol-secrets.sh"
        echo "$GITEA_TOKEN" | docker login -u mcornick --password-stdin git.mcornick.dev
        set -x
        cd clilol
        curl -sfL https://goreleaser.com/static/run | bash
      fi
  - docs: |
      /home/build/clilol-rtd.sh
