---
announce:
  mastodon:
    enabled: true
    server: https://social.lol
archives:
  - builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*.1
    format_overrides:
      - format: zip
        goos: windows
    rlcp: true
aurs:
  - description: "A CLI for omg.lol"
    git_url: "ssh://git@github.com/mcornick/clilol-aur.git"
    homepage: "https://mcornick.com/clilol/"
    license: "MPL-2.0"
    maintainers:
      - "Mark Cornick <mcornick@mcornick.com>"
    name: clilol-bin
    package: |-
      install -Dm755 "./clilol" "${pkgdir}/usr/bin/clilol"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/clilol/LICENSE"
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/clilol.bash" "${pkgdir}/usr/share/bash-completion/completions/clilol"
      install -Dm644 "./completions/clilol.zsh" "${pkgdir}/usr/share/zsh/site-functions/_clilol"
      install -Dm644 "./completions/clilol.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/clilol.fish"
      install -Dm644 "./manpages/*.1" "${pkgdir}/usr/share/man/man1/*.1"
    private_key: "{{ .Env.AUR_KEY }}"
before:
  hooks:
    - go mod tidy
    - bash ./scripts/completions.sh
    - bash ./scripts/manpages.sh
brews:
  - description: A CLI for omg.lol
    homepage: https://mcornick.com/clilol/
    install: |-
      bin.install "clilol"
      bash_completion.install "completions/clilol.bash" => "clilol"
      zsh_completion.install "completions/clilol.zsh" => "_clilol"
      fish_completion.install "completions/clilol.fish"
      man1.install Dir["manpages/*.1"]
    license: MPL-2.0
    tap:
      name: homebrew-tap
      owner: mcornick
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mcornick/clilol/cmd.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets:
      - go_first_class
changelog:
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^docs:"
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  sort: asc
  use: github
checksum:
  name_template: checksums.txt
furies:
  - account: mcornick
gomod:
  proxy: true
kos:
  - bare: true
    build: clilol
    id: clilol-ghcr
    labels:
      io.artifacthub.package.license: MPL-2.0
      io.artifacthub.package.maintainers: '[{"name":"Mark Cornick","email":"mcornick@mcornick.com"}]'
      io.artifacthub.package.readme-url: https://raw.githubusercontent.com/mcornick/clilol/main/README.md
      org.opencontainers.image.description: A CLI for omg.lol
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.version: "{{.Version}}"
    platforms:
      - linux/amd64
      - linux/arm64
    repository: ghcr.io/mcornick/clilol
    tags:
      - latest
      - "{{.Tag}}"
  - bare: true
    build: clilol
    id: clilol-docker
    labels:
      io.artifacthub.package.license: MPL-2.0
      io.artifacthub.package.maintainers: '[{"name":"Mark Cornick","email":"mcornick@mcornick.com"}]'
      io.artifacthub.package.readme-url: https://raw.githubusercontent.com/mcornick/clilol/main/README.md
      org.opencontainers.image.description: A CLI for omg.lol
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.version: "{{.Version}}"
    platforms:
      - linux/amd64
      - linux/arm64
    repository: mcornick/clilol
    tags:
      - latest
      - "{{.Tag}}"
milestones:
  - close: true
nfpms:
  - archlinux:
      packager: Mark Cornick <mcornick@mcornick.com>
    contents:
      - dst: /usr/share/bash-completion/completions/clilol
        file_info:
          mode: 0644
        src: ./completions/clilol.bash
      - dst: /usr/share/fish/vendor_completions.d/clilol.fish
        file_info:
          mode: 0644
        src: ./completions/clilol.fish
      - dst: /usr/share/zsh/vendor-completions/_clilol
        file_info:
          mode: 0644
        src: ./completions/clilol.zsh
      - dst: /usr/share/man/man1/
        file_info:
          mode: 0644
        src: ./manpages/*.1
      - dst: /usr/share/doc/clilol/copyright
        file_info:
          mode: 0644
        src: ./LICENSE
    description: A CLI for omg.lol
    formats:
      - apk
      - archlinux
      - deb
      - rpm
    homepage: https://mcornick.com/clilol/
    license: MPL-2.0
    maintainer: Mark Cornick <mcornick@mcornick.com>
    vendor: Mark Cornick
sboms:
  - artifacts: archive
scoop:
  bucket:
    name: scoop-bucket
    owner: mcornick
  description: A CLI for omg.lol
  homepage: https://mcornick.com/clilol/
  license: MPL-2.0
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ incpatch .Version }}-next"
universal_binaries:
  - replace: true
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
