---
announce:
  mastodon:
    enabled: true
    server: https://social.sdf.org
  skip: '{{ ne .Prerelease "" }}'
archives:
  - builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*.1
    format_overrides:
      - format: zip
        goos: windows
aurs:
  - description: A CLI for omg.lol
    git_url: ssh://git@github.com/mcornick/clilol-aur.git
    homepage: https://clilol.readthedocs.io/
    license: MPL-2.0
    maintainers:
      - Mark Cornick <mark@markcornick.com>
    name: clilol-bin
    package: |
      install -Dm755 "./clilol" "${pkgdir}/usr/bin/clilol"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/clilol/LICENSE"
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/clilol.bash" "${pkgdir}/usr/share/bash-completion/completions/clilol"
      install -Dm644 "./completions/clilol.zsh" "${pkgdir}/usr/share/zsh/site-functions/_clilol"
      install -Dm644 "./completions/clilol.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/clilol.fish"
      install -Dm644 "./manpages/*.1" "${pkgdir}/usr/share/man/man1/*.1"
    private_key: "{{ .Env.AUR_KEY }}"
    skip_upload: auto
before:
  hooks:
    - go mod tidy
    - bash ./scripts/completions.sh
    - bash ./scripts/manpages.sh
brews:
  - description: A CLI for omg.lol
    homepage: https://clilol.readthedocs.io/
    install: |
      bin.install "clilol"
      bash_completion.install "completions/clilol.bash" => "clilol"
      zsh_completion.install "completions/clilol.zsh" => "_clilol"
      fish_completion.install "completions/clilol.fish"
      man1.install Dir["manpages/*.1"]
    license: MPL-2.0
    repository:
      name: homebrew-tap
      owner: mcornick
    skip_upload: auto
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mcornick/clilol/cmd.version={{ .Version }} -X github.com/mcornick/clilol/cmd.commit={{ .ShortCommit }} -X github.com/mcornick/clilol/cmd.date={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets:
      - go_first_class
changelog:
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^docs:"
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  sort: asc
checksum:
  name_template: checksums.txt
docker_signs:
  - args:
      - sign
      - --yes
      - ${artifact}
    artifacts: all
kos:
  - bare: true
    build: clilol
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    labels:
      io.artifacthub.package.license: MPL-2.0
      io.artifacthub.package.maintainers: '[{"name":"Mark Cornick","email":"mark@markcornick.com"}]'
      io.artifacthub.package.readme-url: https://github.com/mcornick/clilol/tree/main/item/README.md
      org.opencontainers.image.description: A CLI for omg.lol
      org.opencontainers.image.name: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.version: "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repository: ghcr.io/mcornick/clilol
    tags:
      - latest
      - "{{ .Tag }}"
milestones:
  - close: true
nfpms:
  - archlinux:
      packager: Mark Cornick <mark@markcornick.com>
    contents:
      - dst: /usr/share/bash-completion/completions/clilol
        file_info:
          mode: 0644
        src: ./completions/clilol.bash
      - dst: /usr/share/fish/vendor_completions.d/clilol.fish
        file_info:
          mode: 0644
        src: ./completions/clilol.fish
      - dst: /usr/share/zsh/vendor-completions/_clilol
        file_info:
          mode: 0644
        src: ./completions/clilol.zsh
      - dst: /usr/share/man/man1/
        file_info:
          mode: 0644
        src: ./manpages/*.1
      - dst: /usr/share/doc/clilol/copyright
        file_info:
          mode: 0644
        src: ./LICENSE
    description: A CLI for omg.lol
    formats:
      - apk
      - archlinux
      - deb
      - rpm
    homepage: https://clilol.readthedocs.io/
    license: MPL-2.0
    maintainer: Mark Cornick <mark@markcornick.com>
    vendor: Mark Cornick
nix:
  - description: A CLI for omg.lol
    extra_install: |
      installManPage ./manpages/*.1
      installShellCompletion ./completions/clilol.{bash,fish,zsh}
    homepage: https://clilol.readthedocs.io/
    license: mpl20
    repository:
      name: nixpkgs
      owner: mcornick
publishers:
  - name: fury.io
    env:
      - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
    cmd: bash ./scripts/fury-upload.sh {{ .ArtifactName }}
    disable: '{{ if ne .Prerelease "" }}true{{ end }}'
release:
  github:
    name: clilol
    owner: mcornick
  prerelease: auto
sboms:
  - artifacts: archive
scoops:
  - description: A CLI for omg.lol
    homepage: https://clilol.readthedocs.io/
    license: MPL-2.0
    repository:
      name: scoop-bucket
      owner: mcornick
    skip_upload: auto
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
snapshot:
  name_template: "{{ incpatch .Version }}-next"
universal_binaries:
  - replace: true
