---
announce:
  bluesky:
    enabled: true
    username: "mcornick.lol"
  mastodon:
    enabled: true
    server: https://social.lol
  skip: '{{ ne .Prerelease "" }}'
archives:
  - builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*.1
    format_overrides:
      - formats: ["zip"]
        goos: windows
aurs:
  - description: A CLI for omg.lol
    git_url: ssh://git@github.com/mcornick/clilol-aur.git
    homepage: https://clilol.readthedocs.io/
    license: MPL-2.0
    maintainers:
      - Mark Cornick <mark@markcornick.com>
    name: clilol-bin
    package: |
      install -Dm755 "./clilol" "${pkgdir}/usr/bin/clilol"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/clilol/LICENSE"
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/clilol.bash" "${pkgdir}/usr/share/bash-completion/completions/clilol"
      install -Dm644 "./completions/clilol.zsh" "${pkgdir}/usr/share/zsh/site-functions/_clilol"
      install -Dm644 "./completions/clilol.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/clilol.fish"
      install -Dm644 "./manpages/*.1" "${pkgdir}/usr/share/man/man1/*.1"
    private_key: "{{ .Env.AUR_KEY }}"
    skip_upload: auto
before:
  hooks:
    - go mod tidy
    - bash ./scripts/completions.sh
    - bash ./scripts/manpages.sh
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mcornick/clilol/cmd.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets:
      - go_first_class
changelog:
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^docs:"
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  sort: asc
checksum:
  name_template: checksums.txt
docker_signs:
  - args:
      - sign
      - --yes
      - ${artifact}
    artifacts: all
homebrew_casks:
  - completions:
      bash: completions/clilol.bash
      zsh: completions/clilol.zsh
      fish: completions/clilol.fish
    conflicts:
      - formula: clilol
    description: A CLI for omg.lol
    homepage: https://clilol.readthedocs.io/
    license: MPL-2.0
    manpages:
      - manpages/clilol.1
      - manpages/clilol-create.1
      - manpages/clilol-create-dns.1
      - manpages/clilol-create-paste.1
      - manpages/clilol-create-picture.1
      - manpages/clilol-create-purl.1
      - manpages/clilol-create-status.1
      - manpages/clilol-create-weblog.1
      - manpages/clilol-delete.1
      - manpages/clilol-delete-account.1
      - manpages/clilol-delete-account-session.1
      - manpages/clilol-delete-dns.1
      - manpages/clilol-delete-paste.1
      - manpages/clilol-delete-picture.1
      - manpages/clilol-delete-purl.1
      - manpages/clilol-delete-status.1
      - manpages/clilol-delete-weblog.1
      - manpages/clilol-get.1
      - manpages/clilol-get-account.1
      - manpages/clilol-get-account-info.1
      - manpages/clilol-get-account-name.1
      - manpages/clilol-get-account-settings.1
      - manpages/clilol-get-address.1
      - manpages/clilol-get-address-availability.1
      - manpages/clilol-get-address-expiration.1
      - manpages/clilol-get-address-info.1
      - manpages/clilol-get-dns.1
      - manpages/clilol-get-email.1
      - manpages/clilol-get-now.1
      - manpages/clilol-get-paste.1
      - manpages/clilol-get-purl.1
      - manpages/clilol-get-service.1
      - manpages/clilol-get-status.1
      - manpages/clilol-get-status-bio.1
      - manpages/clilol-get-theme.1
      - manpages/clilol-get-theme-preview.1
      - manpages/clilol-get-web.1
      - manpages/clilol-get-weblog.1
      - manpages/clilol-get-weblog-config.1
      - manpages/clilol-get-weblog-latest.1
      - manpages/clilol-get-weblog-template.1
      - manpages/clilol-list.1
      - manpages/clilol-list-account.1
      - manpages/clilol-list-account-addresses.1
      - manpages/clilol-list-account-sessions.1
      - manpages/clilol-list-directory.1
      - manpages/clilol-list-dns.1
      - manpages/clilol-list-now.1
      - manpages/clilol-list-pastes.1
      - manpages/clilol-list-pictures.1
      - manpages/clilol-list-purls.1
      - manpages/clilol-list-statuses.1
      - manpages/clilol-list-statuslog.1
      - manpages/clilol-list-themes.1
      - manpages/clilol-list-weblogs.1
      - manpages/clilol-update.1
      - manpages/clilol-update-account.1
      - manpages/clilol-update-account-name.1
      - manpages/clilol-update-account-settings.1
      - manpages/clilol-update-dns.1
      - manpages/clilol-update-email.1
      - manpages/clilol-update-now.1
      - manpages/clilol-update-preference.1
      - manpages/clilol-update-status.1
      - manpages/clilol-update-status-bio.1
      - manpages/clilol-update-web.1
      - manpages/clilol-update-weblog.1
      - manpages/clilol-update-weblog-config.1
      - manpages/clilol-update-weblog-template.1
      - manpages/clilol-update-web-pfp.1
    repository:
      name: homebrew-tap
      owner: mcornick
    skip_upload: false
kos:
  - bare: true
    build: clilol
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    labels:
      io.artifacthub.package.license: MPL-2.0
      io.artifacthub.package.maintainers: '[{"name":"Mark Cornick","email":"mark@markcornick.com"}]'
      io.artifacthub.package.readme-url: https://github.com/mcornick/clilol/tree/main/item/README.md
      org.opencontainers.image.description: A CLI for omg.lol
      org.opencontainers.image.name: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.version: "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repositories:
      - ghcr.io/mcornick/clilol
    tags:
      - latest
      - "{{ .Tag }}"
milestones:
  - close: true
nfpms:
  - archlinux:
      packager: Mark Cornick <mark@markcornick.com>
    contents:
      - dst: /usr/share/bash-completion/completions/clilol
        file_info:
          mode: 0644
        src: ./completions/clilol.bash
      - dst: /usr/share/fish/vendor_completions.d/clilol.fish
        file_info:
          mode: 0644
        src: ./completions/clilol.fish
      - dst: /usr/share/zsh/vendor-completions/_clilol
        file_info:
          mode: 0644
        src: ./completions/clilol.zsh
      - dst: /usr/share/man/man1/
        file_info:
          mode: 0644
        src: ./manpages/*.1
      - dst: /usr/share/doc/clilol/copyright
        file_info:
          mode: 0644
        src: ./LICENSE
    description: A CLI for omg.lol
    formats:
      - apk
      - archlinux
      - deb
      - rpm
    homepage: https://clilol.readthedocs.io/
    license: MPL-2.0
    maintainer: Mark Cornick <mark@markcornick.com>
    vendor: Mark Cornick
nix:
  - description: A CLI for omg.lol
    extra_install: |
      installManPage ./manpages/*.1
      installShellCompletion ./completions/clilol.{bash,fish,zsh}
    homepage: https://clilol.readthedocs.io/
    license: mpl20
    repository:
      name: nixpkgs
      owner: mcornick
    skip_upload: auto
notarize:
  macos:
    - enabled: true
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        wait: false
publishers:
  - name: fury.io
    env:
      - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
    cmd: bash ./scripts/fury-upload.sh {{ .ArtifactName }}
    disable: '{{ if ne .Prerelease "" }}true{{ end }}'
release:
  github:
    name: clilol
    owner: mcornick
  prerelease: auto
sboms:
  - artifacts: archive
scoops:
  - description: A CLI for omg.lol
    homepage: https://clilol.readthedocs.io/
    license: MPL-2.0
    repository:
      name: scoop-bucket
      owner: mcornick
    skip_upload: auto
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
snapshot:
  version_template: "{{ incpatch .Version }}-next"
universal_binaries:
  - replace: true
version: 2
