---
repos:
  - hooks:
      - id: gitleaks
    repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.3
  - hooks:
      - id: go-fmt
      - id: go-vet
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
    repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
