---
pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test ./...
    secrets:
      - CLILOL_ADDRESS
      - CLILOL_APIKEY
      - CLILOL_EMAIL
      - CLILOL_NAME
