---
copyright: Copyright &copy; 2023 Mark Cornick
extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://github.com/mcornick/clilol
    - icon: fontawesome/brands/mastodon
      link: https://social.sdf.org/@mcornick
markdown_extensions:
  - admonition
plugins:
  - search
repo_name: mcornick/clilol
repo_url: https://github.com/mcornick/clilol
site_author: Mark Cornick
site_description: a CLI for omg.lol
site_name: clilol, a CLI for omg.lol
site_url: https://clilol.readthedocs.io/
theme:
  name: readthedocs
