---
copyright: Copyright &copy; 2023 Mark Cornick
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mcornick/clilol
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.sdf.org/@mcornick
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Commands: commands/clilol.md
  - Developer Notes: developer.md
  - Blog: blog/index.md
plugins:
  - blog
  - minify:
      minify_html: true
  - search
  - social
repo_name: mcornick/clilol
repo_url: https://github.com/mcornick/clilol
site_author: Mark Cornick
site_description: a CLI for omg.lol
site_name: clilol, a CLI for omg.lol
site_url: https://clilol.readthedocs.io/
theme:
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: fontawesome/solid/heart
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
