---
jobs:
  fig:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: withfig/push-to-fig-autocomplete-action@74f26098865d70a99aaf2a449c705d7f9bec5ba3 # v1.1.2
        with:
          autocomplete-spec-name: clilol
          integration: cobra
          spec-path: clilol.ts
          token: ${{ secrets.GH_PAT }}
name: fig
"on":
  push:
    tags:
      - v*
permissions:
  contents: read
