---
jobs:
  fig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: withfig/push-to-fig-autocomplete-action@v1
        with:
          autocomplete-spec-name: clilol
          integration: cobra
          spec-path: clilol.ts
          token: ${{ secrets.GH_PAT }}
name: fig
"on":
  push:
    tags:
      - v*
permissions:
  contents: read
