---
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          cache: true
          go-version: ">=1.20.1"
      - uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 # main
        with:
          cosign-release: v2.0.0
      - uses: anchore/sbom-action/download-syft@f65c4834e1593b609f21ba7f2f3f5af6136c33dc # main
        with:
          syft-version: v0.69.0
      - uses: imjasonh/setup-crane@5146f708a817ea23476677995bf2133943b9be0b # v0.1
      - id: import_gpg
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: echo "$GPG_PRIVATE_KEY" > /home/runner/gpgkey.asc && chmod 600 /home/runner/gpgkey.asc
        shell: bash
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          password: ${{ secrets.GH_PAT }}
          registry: ghcr.io
          username: mcornick
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          password: ${{ secrets.DOCKER_TOKEN }}
          username: mcornick
      - env:
          AUR_KEY: ${{ secrets.AUR_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v4.2.0
        with:
          args: release --clean
          distribution: goreleaser-pro
          version: latest
      - run: echo "full_ref_ghcr=$(crane digest ghcr.io/mcornick/clilol:latest --full-ref)" >> $GITHUB_ENV
        shell: bash
      - run: echo "full_ref_docker=$(crane digest mcornick/clilol:latest --full-ref)" >> $GITHUB_ENV
        shell: bash
      - run: cosign sign --yes $full_ref_ghcr
        shell: bash
      - run: cosign sign --yes $full_ref_docker
        shell: bash
      - run: rm /home/runner/gpgkey.asc
        shell: bash
name: goreleaser
"on":
  push:
    tags:
      - "*"
permissions:
  contents: write
  id-token: write
  issues: write
  packages: write
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
