jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          cache: true
          go-version: ">=1.20.2"
      - uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # main
        with:
          cosign-release: v2.0.0
      - uses: anchore/sbom-action/download-syft@ace0b9722a703812d78949ee4ac5b90de1c0eba2 # main
        with:
          syft-version: v0.69.0
      - uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3
      - id: import_gpg
        uses: crazy-max/ghaction-import-gpg@d6f3f49f3345e29369fe57596a3ca8f94c4d2ca7 # v5.4.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: echo "$GPG_PRIVATE_KEY" > /home/runner/gpgkey.asc && chmod 600 /home/runner/gpgkey.asc
        shell: bash
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          password: ${{ secrets.GH_PAT }}
          registry: ghcr.io
          username: mcornick
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          password: ${{ secrets.DOCKER_TOKEN }}
          username: mcornick
      - env:
          AUR_KEY: ${{ secrets.AUR_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
        uses: goreleaser/goreleaser-action@3fa32b8bb5620a2c1afe798654bbad59f9da4906 # v4.4.0
        with:
          args: release --clean
          distribution: goreleaser-pro
          version: latest
      - run: echo "full_ref_ghcr=$(crane digest ghcr.io/mcornick/clilol:latest --full-ref)" >> $GITHUB_ENV
        shell: bash
      - run: echo "full_ref_docker=$(crane digest mcornick/clilol:latest --full-ref)" >> $GITHUB_ENV
        shell: bash
      - run: cosign sign --yes $full_ref_ghcr
        shell: bash
      - run: cosign sign --yes $full_ref_docker
        shell: bash
      - run: rm /home/runner/gpgkey.asc
        shell: bash
# noinspection YAMLSchemaValidation
name: goreleaser
# noinspection YAMLSchemaValidation
"on":
  push:
    tags:
      - "*"
# noinspection YAMLSchemaValidation
permissions:
  contents: write
  id-token: write
  issues: write
  packages: write
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
