jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          cache: true
          go-version: ">=1.20.2"
      - uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 # main
        with:
          cosign-release: v2.0.0
      - uses: anchore/sbom-action/download-syft@ea7104d7995265c38477a059bd139e80702ff245 # main
        with:
          syft-version: v0.69.0
      - uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3
      - id: import_gpg
        uses: crazy-max/ghaction-import-gpg@72b6676b71ab476b77e676928516f6982eef7a41 # v5.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: echo "$GPG_PRIVATE_KEY" > /home/runner/gpgkey.asc && chmod 600 /home/runner/gpgkey.asc
        shell: bash
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          password: ${{ secrets.GH_PAT }}
          registry: ghcr.io
          username: mcornick
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          password: ${{ secrets.DOCKER_TOKEN }}
          username: mcornick
      - env:
          AUR_KEY: ${{ secrets.AUR_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
        uses: goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7 # v4.3.0
        with:
          args: release --clean
          distribution: goreleaser-pro
          version: latest
      - run: echo "full_ref_ghcr=$(crane digest ghcr.io/mcornick/clilol:latest --full-ref)" >> $GITHUB_ENV
        shell: bash
      - run: echo "full_ref_docker=$(crane digest mcornick/clilol:latest --full-ref)" >> $GITHUB_ENV
        shell: bash
      - run: cosign sign --yes $full_ref_ghcr
        shell: bash
      - run: cosign sign --yes $full_ref_docker
        shell: bash
      - run: rm /home/runner/gpgkey.asc
        shell: bash
# noinspection YAMLSchemaValidation
name: goreleaser
# noinspection YAMLSchemaValidation
"on":
  push:
    tags:
      - "*"
# noinspection YAMLSchemaValidation
permissions:
  contents: write
  id-token: write
  issues: write
  packages: write
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
