---
jobs:
  deploy:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: pip install git+https://${GH_PAT}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install mkdocs-git-revision-date-localized-plugin pillow cairosvg mike
      - run: git config user.name mcornick
      - run: git config user.email mcornick@mcornick.com
      - run: mike deploy --push --update-aliases 0.9 latest --config-file mkdocs.insiders.yml
name: mkdocs
"on":
  push:
    branches:
      - main
permissions:
  contents: write
