---
jobs:
  deploy:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: ">=1.20.1"
      - env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: pip install git+https://${GH_PAT}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install mkdocs-git-revision-date-localized-plugin pillow cairosvg
      - run: ./scripts/jsonSchema.sh
      - run: mkdocs gh-deploy --force --config-file mkdocs.insiders.yml
name: mkdocs
"on":
  push:
    tags:
      - "*"
permissions:
  contents: write
