---
jobs:
  deploy:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: ">=1.20.2"
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: 3.x
      - env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: pip install git+https://${GH_PAT}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install mkdocs-git-revision-date-localized-plugin pillow cairosvg mike
      - run: git config user.name mcornick
      - run: git config user.email mcornick@mcornick.com
      - run: bash ./scripts/jsonSchema.sh
      - run: mike deploy --push --update-aliases 1.0 latest --config-file mkdocs.insiders.yml --force
name: mkdocs
"on":
  push:
    tags:
      - v*
permissions:
  contents: write
