#file: noinspection GrazieInspection
jobs:
  deploy:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: ">=1.20.2"
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
        with:
          python-version: 3.x
      - env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: pip install git+https://${GH_PAT}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install mkdocs-git-revision-date-localized-plugin pillow cairosvg mike
      - run: git config user.name mcornick
      - run: git config user.email mcornick@mcornick.com
      - run: bash ./scripts/jsonSchema.sh
      - run: mike deploy --push --update-aliases 1.0 latest --config-file mkdocs.insiders.yml --force
name: mkdocs
"on":
  push:
    tags:
      - v*
permissions:
  contents: write
